### PR TITLE
added cit to zip convert

### PR DESCRIPTION
**Pull request by savanipoojan78**
This PR is related to Issue:- 2
i have added one api which internally called mongo to convert city name to its zip code.

i would also like to suggestion somethig that right now this application is not fully mvc architecure 
and i would like to help you to move this appllication to mvc architecture

### CODE REVIEW

**Comment by LiaTsernant** [comment]
@savanipoojan78 Great! Thank you for this example! I will mark it as accepted. Please, let me know if it didn't count in your hacktoberfest account, I will make sure it will :)
Just a little bit later I will merge all pieces of the project.

Feel free to refactor this app as you want. 
I will make sure every effort doesn't disappear for nothing :)

**Comment by savanipoojan78** [comment]
it says in review in hacktoberfest account.

**Comment by LiaTsernant** [comment]
@savanipoojan78 I have the same my PR in other project. I suppose it is fine. 
If it is a clock icon, then we have the same :) 
Screenshot from 2020-10-05 00-54-19

**Comment by savanipoojan78** [comment]
thanks for clarification

**Pull request merged**
